"""Initial migration

Revision ID: 69343e01e4da
Revises: 
Create Date: 2023-07-13 01:39:23.870081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69343e01e4da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palette')
    with op.batch_alter_table('color_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_palette', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('color_entry', schema=None) as batch_op:
        batch_op.drop_column('random_palette')

    op.create_table('palette',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), nullable=False),
    sa.Column('one', sa.VARCHAR(length=7), nullable=False),
    sa.Column('two', sa.VARCHAR(length=7), nullable=False),
    sa.Column('three', sa.VARCHAR(length=7), nullable=False),
    sa.Column('four', sa.VARCHAR(length=7), nullable=False),
    sa.Column('five', sa.VARCHAR(length=7), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
